/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/carev/neutralTheme.ts
 * Command: astryx theme build src/theme/carev/neutralTheme.ts
 * Generated: 2026-07-31T13:52:46.105Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const neutralTheme: DefinedTheme;
