/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/carev/neutralTheme.ts
 * Command: astryx theme build src/theme/carev/neutralTheme.ts
 * Generated: 2026-07-31T01:33:05.222Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const neutralTheme: DefinedTheme;
