/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/carev/neutralTheme.ts
 * Command: astryx theme build src/theme/carev/neutralTheme.ts --out src/theme/carev/neutral.css
 * Generated: 2026-10-04T07:38:47.307Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const neutralTheme: DefinedTheme;
